### ISSUE TITLE
OTP with ODBC module

### ISSUE THREAD

**Issue by matheusmatos** [nerves-project/nerves_system_br#119]
Hi guys,

I have tried to use the [ODBC module](http://erlang.org/doc/man/odbc.html) with Nerves installed on a RaspberryPI, and it's not available :(

How can I compile Nerves from source using OTP with ODBC activated?

P.S: That's an awesome project!

**Comment by mobileoverlord** [comment]
@matheusmatos the default systems that we provide do not have ODBC enabled by default. You can however enable unixODBC in a custom nerves system which will then enabled it to be compiled into Erlang.

You can create a custom system by following the instructions found here:
https://hexdocs.pm/nerves/systems.html#customizing-your-own-nerves-system

Once you create your custom system, you are going to use `make menuconfig` to edit the buildroot configuration and enable `BR2_PACKAGE_UNIXODBC=y`

If you encounter problems let us know and we can reopen the issue.
Thanks 😄
