### ISSUE TITLE
Support for reverting back to known-good firmware

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_br#23]
The `fwup` configurations for firmware update with Nerves make it possible to revert to previous working firmware, but there's no build-in support for actually doing that. This functionality is needed for the CI framework where it is anticipated that bad firmware images will be loaded on a semi-regular basis. Beyond that, the functionality is required in most production environments especially where manual intervention is impractical.

The upcoming work by @ghitchens on `firmware.ex` will address this.

**Comment by mobileoverlord** [comment]
@ghitchens I'll assist in the docs and merging. I would like this to be the start of the `nerves_runtime` which can be included with the `nerves` app containing the build tools.

**Comment by fhunleth** [comment]
I have firmware revert support working in most of the officially supported systems and @mobileoverlord added a revert helper function to `Nerves.Runtime`. It's getting close!

**Comment by fhunleth** [comment]
`Nerves.Runtime.revert` should get most people there and custom systems can add automatic revert support.
