### ISSUE TITLE
Use `/usr/bin/env bash` instead of `/bin/bash`

### ISSUE THREAD

**Issue by the-kenny** [nerves-project/nerves_system_br#240]
### Current behavior

Multiple scripts use hardcoded `/bin/bash` as their shebang line. This fails for systems where `bash` isn't in `/bin` (one notable example is [NixOS](https://nixos.org)).

### Expected behavior

Shell scripts should use `/usr/bin/env bash` as their shebang line, automatically resolving `bash` from `$PATH`.

This likely isn't limited to `nerves_system_br` but may span multiple projects in this organization. I'll hesitate from opening issues / pull requests for this before you people decide if this will get fixed :-)

**Comment by fhunleth** [comment]
Thanks for opening this issue. This seems like an important thing to fix and I don't know of any downsides. Please go ahead and send PRs.

**Comment by fhunleth** [comment]
@the-kenny I made a pass at the change. I have a feeling like there's more work to do to get this working on NixOS this is a start. I'll try it locally for a while and if I don't notice any issues or hear otherwise from you, I'll merge it.

**Comment by the-kenny** [comment]
Thanks for this! If you need any help on NixOS I’m here to help. I’m a bit busy with work right now, but I’ll try to take a look at your changes tomorrow. If I find some more time I can tackle other issues coming up too.

**Comment by fhunleth** [comment]
Closing since the change was made in a past release. If there is more NixOS work, please feel free to open up more issues.
