### ISSUE TITLE
Modify `erlinit.config` on the application side

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_br#25]
Currently it's not easy to modify `/etc/erlinit.config` when building an application. This would be useful to enable/disable the hang-on-error feature (e.g. when building dev or prod releases) and also to support non-default tty's, helper programs, and other debugging features.

Fixing this currently requires squashfs overlay merging in Nerves.

**Comment by kfatehi** [comment]
At this point, what's the best way to disable hang-on-error?

**Comment by mobileoverlord** [comment]
erlinit.config can be overwritten by supplying your own rootfs-additions in your mix project. Documentation for it can be found here: https://hexdocs.pm/nerves/advanced-configuration.html#overwriting-files-in-the-root-file-system
