### ISSUE TITLE
Try/test rpi-0.3.3 pkg for bakeware [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_system_br#49]
(From the #nerves channel TODO list I've been culling):

Date: 23 Feb
Participants: All
Details:
(19Mar- this one may be out-of-date?)
- Try/test rpi-0.3.3 pkg for bakeware
  - pi zero support
  - pi images coming with WPA supplicant 
  - a handful of WIFI drivers
  - still work to be done for official wifi support, but getting much closer

**Comment by GregMefford** [comment]
@ChuckLutz: I believe this issue has been resolved. We now have full support for Pi Zero and rudimentary support for some common WiFi adapters.

Thanks again for capturing this and the other issues that came up in Slack! :balloon: :bowtie:
