### ISSUE TITLE
Need updated how-to video [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_system_br#51]
(From the #nerves channel TODO list I've been culling):
Date: 23 Feb
Participants: chuck_lutz, gregmefford
Details:
- Need updated how-to vid
- (19 Mar): jschneck's 3 Mar meetup vid might help a bit for now: https://www.youtube.com/watch?v=V7SAb02PaUU

**Comment by mobileoverlord** [comment]
This issue should be moved to https://github.com/nerves-project/nerves-project.github.com
There we should discuss the best way to "not confuse people when mentioning things like bake and other legacy things." @ChuckLutz please coordinate with @GregMefford I know he has thoughts in this area already
