### ISSUE TITLE
Nerves training site [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_system_br#52]
(From the #nerves channel TODO list I've been culling):
Date: 23 Feb
Participants: tmecklem, gregmefford, Gaslight folks ...
Details:
- Nerves training site
- (19 Mar): Not sure if this refers to updates to the http://nerves-project.org/learn/ page or something separate

**Comment by GregMefford** [comment]
I think we can close this issue now that we have a usable Getting Started guide posted here: https://hexdocs.pm/nerves/getting-started.html

We still want to work on more guides for specific things, but I think we should track those as separate issues.

Thanks for capturing this!
