### ISSUE TITLE
Writeup on using SPI in nerves [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_system_br#54]
(From the #nerves channel TODO list I've been culling):
Date: 19 Feb
Participants: code0100fun, jschneck
Details:
- Writeup on using SPI in nerves
  - jschneck maybe already has something in progress?

**Comment by mobileoverlord** [comment]
I am not sure this belongs here. I guess overall it would be nice to have some sort of preliminary overview to using ElixrAle with Nerves. SPI is already documented there. @fhunleth thoughts? or close

**Comment by fhunleth** [comment]
I agree - the SPI should be documented in elixir_ale.
