### ISSUE TITLE
Running under Vagrant [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_system_br#56]
(From the #nerves channel TODO list I've been culling):
Date: ?? March
Participants: bordeltabernacle, requisite0, gregmefford
Details:
- bordeltabernacle's work to get it running on (under?) Vagrant - https://github.com/bordeltabernacle/vagrant-nerves
- Later, on 16 March, requisite0 reported getting it running under Vagrant as part of an interesting project ("I've got elixir_serial working with Phoenix and SQLite for dealing with MySensors data over REST.")

**Comment by mobileoverlord** [comment]
`nerves 0.4` has support for running under Docker using either Docker or Docker for Mac. This will fulfill the intentions of this issue, and pave the way for anyone who would want to use Vagrant to write their own provider using the `Nerves.Package.Provider` behaviour
