### ISSUE TITLE
Question on ERTS on same arch/different distro [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves_system_br#57]
(From the #nerves channel TODO list I've been culling):
Date: 01 Mar
Participants: vy, jschneck
Details:
- Question as to whether ERTS can be shared same arch, different distro
  - Idea is to host a mirror of compiled ERTS for different archs as an "open source thing"
  - (Main motivation is to make it easier for Exrm to cross-compile Elixir releases)

**Comment by fhunleth** [comment]
Closing old issue. ERTS will be kept distributed with the systems to avoid any ABI, architecture, etc. issues with trying to share it.
