### ISSUE TITLE
Onion Omega support

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_br#60]
Add support for the Onion Omega platform: https://onion.io/

Moved here from https://github.com/nerves-project/nerves-examples/issues/3

**Comment by ramstein74** [comment]
You should start a kickstarter project...

**Comment by fhunleth** [comment]
Fwiw, I have an Onion Omega on my desk. I think that it would be a great Nerves platform.

**Comment by ramstein74** [comment]
I also have another onion in my desk and i regret having bought it.

But if nerves come to onion it would be a different story...

2016-03-21 1:05 GMT+00:00 Frank Hunleth <notifications@github.com>:

**Comment by brienw** [comment]
👍

**Comment by fhunleth** [comment]
I'm not planning on porting to the Onion any time soon, but I am making progress on a board which is very similar and normally runs OpenWRT. The docs aren't ready yet, but you can see progress at https://github.com/nerves-project/nerves_system_linkit. If someone is interested in doing an Onion port, that repository would likely help. I don't think that it will be an easy port, though, since the Onion has a relatively small NAND Flash.

**Comment by heri16** [comment]
+1

**Comment by ramstein74** [comment]
new onion omega2 arriving with more memory (128Mb)

https://www.kickstarter.com/projects/onion/omega2-5-iot-computer-with-wi-fi-powered-by-linux?ref=nav_search

2016-07-02 10:34 GMT+01:00 heri16 <notifications@github.com>:

**Comment by fhunleth** [comment]
No reported progress for a long time and no work is planned on this from the core Nerves team, so closing.
