### ISSUE TITLE
scrub-otp-release.sh and newer versions of 'file'

### ISSUE THREAD

**Issue by ejc123** [nerves-project/nerves_system_br#92]
I am running two different Linux systems, one is Ubuntu 16.04, the other is Arch.  The Ubuntu system works file, but the arch system fails with:

```Updating base firmware image with Erlang release...
scrub-otp-release.sh: ERROR: Unexpected executable format for '/home/ejc/projects/nerves/demo/_nerves-tmp/rootfs-additions/srv/erlang/lib/nerves_wpa_supplicant-0.3.0/priv/wpa_ex'

Got:
 ELF 32-bit LSB executable, ARM, EABI5 version 1, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.12.55, with debug_info

If binary, expecting:
 ELF 32-bit LSB executable, ARM, EABI5 version 1, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.12.55
```
The Ubuntu system has file-5.25, the arch system file-5.31.  They use different version of magic file.  The binary in questions is identical between systems, but the output from file is different.  It seems the newer version of file adds 'with debug_info'

**Comment by fhunleth** [comment]
Ugh. It may be necessary for me to rethink about how this check is done. The latest Buildroot version added some logic in this area. I really appreciate your patch, though, so I can put this off a little longer. Thanks!
